# Setup
title:               Daniel Maloney
tagline:             'A CS/Math/Data-Science student at UW-Madison'
description:         'A blog of ramblings about soccer analytics, among other things.'
url:                 dpmaloney.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniel Maloney
  url:               https://www.linkedin.com/in/dpmaloney/
  email:             dpcmaloney@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: UA-146052-15
